### ISSUE TITLE
Leave travis CI and use another CI/CD system

### ISSUE THREAD

**Issue by Khalian** [Khalian/Modulo12#8]
Travis org will be shut down soon (ish). All projects would be migrated to travis com and we would have to pay eventually.

This task is to migrate away from travis. Possible answers are shippable or circle CI. I am open to other suggestions.

**Comment by ambertide** [comment]
Maybe you can try GitHub Actions?

**Comment by Khalian** [comment]
Good idea. I will take a look at that too.

**Comment by Khalian** [comment]
This might be trickier than I thought. Both github actions and circle CI seem to be using docker and docker prevents outbound internet conn.

The tests for music xml fail, since i have to acquire the DTD from a url as a part of the run.

**Comment by Khalian** [comment]
Moved off of travis to github actions. https://github.com/Khalian/Modulo12/pull/14 thanks @ambertide for the suggestion.

**Comment by ambertide** [comment]
Oh, I am glad you were able to solve the issue, I refrained from commenting further before as I was afraid of spamming the thread since I didn't have much to contribute as I am unfamiliar with your system, best of luck in the project in general
